version: "3.8"
services:
  pokemon-translator:
    container_name: php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/app
      - /app/vendor

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
        - pokemon-translator
    ports:
        - "5000:80"
    volumes:
        - .:/app
        - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
